<?php
session_start();
require '../db_connect.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
  header('Location: ../index.php');
  exit;
}

$startDate = $_GET['start'] ?? date('Y-m-01');
$endDate = $_GET['end'] ?? date('Y-m-d');

$orders = $conn->query("
  SELECT 
    o.id,
    u.name as customer_name,
    u.email,
    o.options,
    o.service_mode,
    o.payment_method,
    o.total_cost,
    o.status,
    o.payment_status,
    o.created_at
  FROM orders o
  JOIN users u ON o.user_id = u.id
  WHERE DATE(o.created_at) BETWEEN '$startDate' AND '$endDate'
  ORDER BY o.created_at DESC
");

$summary = $conn->query("
  SELECT 
    COUNT(*) as total_orders,
    SUM(CASE WHEN payment_status = 'Paid' THEN total_cost ELSE 0 END) as total_revenue,
    AVG(total_cost) as avg_order_value,
    SUM(CASE WHEN payment_status = 'Paid' THEN 1 ELSE 0 END) as paid_orders,
    SUM(CASE WHEN payment_status != 'Paid' THEN total_cost ELSE 0 END) as unpaid_amount
  FROM orders
  WHERE DATE(created_at) BETWEEN '$startDate' AND '$endDate'
")->fetch_assoc();

header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename=laundry_report_' . $startDate . '_to_' . $endDate . '.xls');
header('Pragma: no-cache');
header('Expires: 0');

?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid black; padding: 8px; text-align: left; }
th { background-color: #2563eb; color: white; font-weight: bold; }
.summary { background-color: #f3f4f6; font-weight: bold; }
.header { background-color: #2563eb; color: white; font-size: 18px; font-weight: bold; text-align: center; padding: 15px; }
</style>
</head>
<body>

<div class="header">LAUNDRY MANAGEMENT SYSTEM - SALES REPORT</div>
<p><strong>Report Period:</strong> <?= $startDate ?> to <?= $endDate ?></p>
<p><strong>Generated:</strong> <?= date('Y-m-d H:i:s') ?></p>
<p><strong>Generated By:</strong> <?= htmlspecialchars($_SESSION['name']) ?></p>

<h2>Summary Statistics</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  <tr><td>Total Orders</td><td><?= number_format($summary['total_orders']) ?></td></tr>
  <tr><td>Total Revenue</td><td>PHP <?= number_format($summary['total_revenue'], 2) ?></td></tr>
  <tr><td>Average Order Value</td><td>PHP <?= number_format($summary['avg_order_value'], 2) ?></td></tr>
  <tr><td>Paid Orders</td><td><?= number_format($summary['paid_orders']) ?></td></tr>
  <tr><td>Unpaid Amount</td><td>PHP <?= number_format($summary['unpaid_amount'], 2) ?></td></tr>
</table>

<br><br>

<h2>Detailed Order List</h2>
<table>
  <thead>
    <tr>
      <th>Order ID</th>
      <th>Customer Name</th>
      <th>Email</th>
      <th>Services</th>
      <th>Service Mode</th>
      <th>Payment Method</th>
      <th>Total Amount</th>
      <th>Order Status</th>
      <th>Payment Status</th>
      <th>Order Date</th>
    </tr>
  </thead>
  <tbody>
    <?php 
    $totalRevenue = 0;
    while ($order = $orders->fetch_assoc()): 
      $totalRevenue += $order['total_cost'];
    ?>
    <tr>
      <td><?= $order['id'] ?></td>
      <td><?= htmlspecialchars($order['customer_name']) ?></td>
      <td><?= htmlspecialchars($order['email']) ?></td>
      <td><?= htmlspecialchars($order['options']) ?></td>
      <td><?= htmlspecialchars($order['service_mode']) ?></td>
      <td><?= htmlspecialchars($order['payment_method']) ?></td>
      <td>PHP <?= number_format($order['total_cost'], 2) ?></td>
      <td><?= htmlspecialchars($order['status']) ?></td>
      <td><?= htmlspecialchars($order['payment_status']) ?></td>
      <td><?= $order['created_at'] ?></td>
    </tr>
    <?php endwhile; ?>
    <tr class="summary">
      <td colspan="6"><strong>TOTAL</strong></td>
      <td><strong>PHP <?= number_format($totalRevenue, 2) ?></strong></td>
      <td colspan="3"></td>
    </tr>
  </tbody>
</table>

<br><br>
<p style="text-align: center; color: #666; font-size: 12px;">
  © <?= date('Y') ?> Laundry Management System. All rights reserved.<br>
  This is a computer-generated document. No signature required.
</p>

</body>
</html>