<?php
session_start();
require '../db_connect.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
  header('Location: ../index.php');
  exit;
}

$startDate = $_GET['start'] ?? date('Y-m-01');
$endDate = $_GET['end'] ?? date('Y-m-d');

$orders = $conn->query("
  SELECT 
    o.id,
    u.name as customer_name,
    u.email,
    o.options,
    o.service_mode,
    o.payment_method,
    o.total_cost,
    o.status,
    o.payment_status,
    o.created_at
  FROM orders o
  JOIN users u ON o.user_id = u.id
  WHERE DATE(o.created_at) BETWEEN '$startDate' AND '$endDate'
  ORDER BY o.created_at DESC
");

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=laundry_orders_' . $startDate . '_to_' . $endDate . '.csv');

$output = fopen('php://output', 'w');
fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));

fputcsv($output, [
  'Order ID',
  'Customer Name',
  'Customer Email',
  'Services',
  'Service Mode',
  'Payment Method',
  'Total Amount',
  'Order Status',
  'Payment Status',
  'Order Date'
]);

while ($order = $orders->fetch_assoc()) {
  fputcsv($output, [
    $order['id'],
    $order['customer_name'],
    $order['email'],
    $order['options'],
    $order['service_mode'],
    $order['payment_method'],
    number_format($order['total_cost'], 2),
    $order['status'],
    $order['payment_status'],
    $order['created_at']
  ]);
}

fputcsv($output, []);
fputcsv($output, ['SUMMARY']);
fputcsv($output, []);

$summary = $conn->query("
  SELECT 
    COUNT(*) as total_orders,
    SUM(CASE WHEN payment_status = 'Paid' THEN total_cost ELSE 0 END) as total_revenue,
    AVG(total_cost) as avg_order_value,
    SUM(CASE WHEN payment_status = 'Paid' THEN 1 ELSE 0 END) as paid_orders,
    SUM(CASE WHEN payment_status != 'Paid' THEN total_cost ELSE 0 END) as unpaid_amount
  FROM orders
  WHERE DATE(created_at) BETWEEN '$startDate' AND '$endDate'
")->fetch_assoc();

fputcsv($output, ['Total Orders', $summary['total_orders']]);
fputcsv($output, ['Total Revenue', 'PHP ' . number_format($summary['total_revenue'], 2)]);
fputcsv($output, ['Average Order Value', 'PHP ' . number_format($summary['avg_order_value'], 2)]);
fputcsv($output, ['Paid Orders', $summary['paid_orders']]);
fputcsv($output, ['Unpaid Amount', 'PHP ' . number_format($summary['unpaid_amount'], 2)]);
fputcsv($output, []);
fputcsv($output, ['Report Generated', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated By', $_SESSION['name']]);

fclose($output);
exit;
?>